[Bug Fixed] add `scaler.update()` in MNIST examples (#45)
**Description**
Fix the following bug introduced in the PR #36 . The `scaler.update()`
should be called after `scaler.step(optimizer)`.

```
Traceback (most recent call last):
  File "mnist.py", line 181, in <module>
    main()
  File "mnist.py", line 172, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "mnist.py", line 73, in train
    scaler.step(optimizer)
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 321, in step
    raise RuntimeError("step() has already been called since the last update().")
RuntimeError: step() has already been called since the last update().
```

**Major Revision**
- add `scaler.update()` after `scaler.step(optimizer)`